CREATE TABLE 
 Item (
  id SERIAL NOT NULL,
  genre_id INT,
  author_id INT,
  label_id INT,
  source_id INT,
  public_date DATE NOT NULL,
  archived BOOLEAN,
  FOREIGN KEY(genre_id) REFERENCES Genre(id),
  FOREIGN KEY(author_id) REFERENCES Author(id)
  FOREIGN KEY(label_id) REFERENCES Label(id)
  PRIMARY KEY(id)
 );

 CREATE TABLE Genre(
  id SERIAL NOT NULL,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
 );

 CREATE TABLE Source(
  id SERIAL NOT NULL,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
 );

 CREATE TABLE Author(
  id SERIAL NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
 );

 CREATE TABLE Label(
  id SERIAL NOT NULL,
  title VARCHAR(100) NOT NULL,
  color VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
 );

 CREATE TABLE MusicAlbum(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  on_spotify BOOLEAN NOT NULL,
  public_date DATE NOT NULL,
  genre_id INT NULL,
  author_id INT NULL,
  label_id INT NULL,
  source_id INT NULL,
  FOREIGN KEY (genre_id) REFERENCES  Genre(id),
  FOREIGN KEY (author_id) REFERENCES Author(id),
  FOREIGN KEY (label_id) REFERENCES Label(id),
  FOREIGN KEY (source_id) REFERENCES Source(id),
  archived BOOLEAN NOT NULL,
  PRIMARY KEY(id)
 );

 CREATE TABLE Book(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  publisher VARCHAR(100) NOT NULL,
  cover_state VARCHAR(100) NOT NULL,
  public_date DATE NOT NULL,
  genre_id INT NULL,
  author_id INT NULL,
  label_id INT NULL,
  source_id INT NULL,
  FOREIGN KEY (genre_id) REFERENCES  Genre(id),
  FOREIGN KEY (author_id) REFERENCES Author(id),
  FOREIGN KEY (label_id) REFERENCES Label(id),
  FOREIGN KEY (source_id) REFERENCES Source(id),
  archived BOOLEAN NOT NULL,
  PRIMARY KEY(id)
 );